## Database
#spring.datasource.url=jdbc:mysql://localhost/starwars?useSSL=false
#spring.datasource.username=user
#spring.datasource.password=123456
#
## Schema Initialization
#spring.jpa.hibernate.ddl-auto=update

server:
  port: 8080

spring:
  application:
    name: api


  datasource:
    url: jdbc:mysql://localhost:3306/starwars
    username: starwars
    password: starwars

  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect